name: MedalCabinet
version: ${project.version}
main: com.mcatk.medalcabinet.MedalCabinet
authors: [ soto ]
softdepend: [ PlaceholderAPI ]
commands:
  medal:
    description: main command
  medalshow:
    description: main command
  medaladmin:
    description: admin command